# Generated by Django 5.1.6 on 2025-03-06 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Завод", "Завод"),
                            ("Розничная сеть", "Розничная сеть"),
                            (
                                "Индивидуальный предприниматель",
                                "Индивидуальный предприниматель",
                            ),
                        ],
                        default="Завод",
                        help_text="Укажите название звена сети",
                        max_length=30,
                        verbose_name="Название звена сети",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите адрес электронной почты",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Укажите страну дислокации звена сети",
                        max_length=50,
                        verbose_name="Название страны дислокации звена сети",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Укажите город дислокации звена сети",
                        max_length=50,
                        verbose_name="Название города дислокации звена сети",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Укажите улицу дислокации звена сети",
                        max_length=50,
                        verbose_name="Название улицы дислокации звена сети",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        help_text="Укажите улицу дислокации звена сети",
                        max_length=50,
                        null=True,
                        verbose_name="Название улицы дислокации звена сети",
                    ),
                ),
                (
                    "supplier_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Укажите уровень поставщика",
                        null=True,
                        verbose_name="Уровень поставщика",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=None,
                        help_text="Укажите задолженность перед поставщиком",
                        max_digits=20,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Укажите продукты",
                        to="products.product",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network_links.link",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
                "ordering": [
                    "title",
                    "email",
                    "country",
                    "city",
                    "street",
                    "house_number",
                    "supplier",
                    "supplier_level",
                    "debt",
                    "created_at",
                ],
            },
        ),
    ]
